-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 14:19:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema edukit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `edukit` ;

-- -----------------------------------------------------
-- Schema edukit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edukit` DEFAULT CHARACTER SET utf8 ;
USE `edukit` ;

-- -----------------------------------------------------
-- Table `edukit`.`historiales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`historiales` ;

CREATE TABLE IF NOT EXISTS `edukit`.`historiales` (
  `id_Historiales` INT NOT NULL AUTO_INCREMENT,
  `promedio_mensual` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_Historiales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`personas` ;

CREATE TABLE IF NOT EXISTS `edukit`.`personas` (
  `RUT` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `id_Historiales` INT NOT NULL,
  PRIMARY KEY (`RUT`),
  CONSTRAINT `fk_personas_historiales1`
    FOREIGN KEY (`id_Historiales`)
    REFERENCES `edukit`.`historiales` (`id_Historiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `RUT_UNIQUE` ON `edukit`.`personas` (`RUT` ASC) VISIBLE;

CREATE INDEX `fk_personas_historiales1_idx` ON `edukit`.`personas` (`id_Historiales` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `edukit`.`tipos_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`tipos_usuarios` ;

CREATE TABLE IF NOT EXISTS `edukit`.`tipos_usuarios` (
  `id_tipo_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion_tipo` VARCHAR(300) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_tipo_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`cargo` ;

CREATE TABLE IF NOT EXISTS `edukit`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NOT NULL,
  `descripcion_cargo` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `edukit`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre_asig` VARCHAR(45) NOT NULL,
  `descripcion_asig` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`tipos_institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`tipos_institucion` ;

CREATE TABLE IF NOT EXISTS `edukit`.`tipos_institucion` (
  `id_tipos_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion_tipo` VARCHAR(300) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_tipos_institucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`instituciones` ;

CREATE TABLE IF NOT EXISTS `edukit`.`instituciones` (
  `id_instituciones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `id_tipos_institucion` INT NOT NULL,
  PRIMARY KEY (`id_instituciones`),
  CONSTRAINT `fk_instituciones_tipos_institucion1`
    FOREIGN KEY (`id_tipos_institucion`)
    REFERENCES `edukit`.`tipos_institucion` (`id_tipos_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_instituciones_tipos_institucion1_idx` ON `edukit`.`instituciones` (`id_tipos_institucion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `edukit`.`tipo_capacitaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`tipo_capacitaciones` ;

CREATE TABLE IF NOT EXISTS `edukit`.`tipo_capacitaciones` (
  `id_tipo_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  `descripcion_tipo` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_tipo_capacitaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edukit`.`capacitaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`capacitaciones` ;

CREATE TABLE IF NOT EXISTS `edukit`.`capacitaciones` (
  `id_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion_horas` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `id_tipo_capacitaciones` INT NOT NULL,
  PRIMARY KEY (`id_capacitaciones`),
  CONSTRAINT `fk_capacitaciones_tipo_capacitaciones1`
    FOREIGN KEY (`id_tipo_capacitaciones`)
    REFERENCES `edukit`.`tipo_capacitaciones` (`id_tipo_capacitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_capacitaciones_tipo_capacitaciones1_idx` ON `edukit`.`capacitaciones` (`id_tipo_capacitaciones` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `edukit`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edukit`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `edukit`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `passwords` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_by` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `id_tipo_usuarios` INT NOT NULL,
  `RUT` INT NOT NULL,
  `id_cargo` INT NULL,
  `id_asignatura` INT NULL,
  `id_instituciones` INT NULL,
  `id_capacitaciones` INT NULL,
  PRIMARY KEY (`id_usuarios`),
  CONSTRAINT `fk_usuarios_tipos_usuarios`
    FOREIGN KEY (`id_tipo_usuarios`)
    REFERENCES `edukit`.`tipos_usuarios` (`id_tipo_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`RUT`)
    REFERENCES `edukit`.`personas` (`RUT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `edukit`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_asignatura1`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `edukit`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_instituciones1`
    FOREIGN KEY (`id_instituciones`)
    REFERENCES `edukit`.`instituciones` (`id_instituciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_capacitaciones1`
    FOREIGN KEY (`id_capacitaciones`)
    REFERENCES `edukit`.`capacitaciones` (`id_capacitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarios_tipos_usuarios_idx` ON `edukit`.`usuarios` (`id_tipo_usuarios` ASC) VISIBLE;
CREATE INDEX `fk_usuarios_personas1_idx` ON `edukit`.`usuarios` (`RUT` ASC) VISIBLE;
CREATE INDEX `fk_usuarios_cargo1_idx` ON `edukit`.`usuarios` (`id_cargo` ASC) VISIBLE;
CREATE INDEX `fk_usuarios_asignatura1_idx` ON `edukit`.`usuarios` (`id_asignatura` ASC) VISIBLE;
CREATE INDEX `fk_usuarios_instituciones1_idx` ON `edukit`.`usuarios` (`id_instituciones` ASC) VISIBLE;
CREATE INDEX `fk_usuarios_capacitaciones1_idx` ON `edukit`.`usuarios` (`id_capacitaciones` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;